const {chromium}=require('playwright');
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');

(async()=>{
  const allowed=new Set(['v3-beta.html','v3-beta.js','v3-beta.css','workflow-v3-beta.js']);
  const server=http.createServer((req,res)=>{const name=req.url==='/'?'v3-beta.html':req.url.slice(1);if(!allowed.has(name)){res.writeHead(404);res.end();return}res.setHeader('Content-Type',name.endsWith('.css')?'text/css':name.endsWith('.js')?'text/javascript':'text/html');res.end(fs.readFileSync(path.join(__dirname,'../web',name)))});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  let browser;
  try{
    browser=await chromium.launch({channel:'msedge',headless:true});
    const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
    page.on('pageerror',error=>errors.push(error.message));
    await page.addInitScript(()=>localStorage.setItem('kendo-h3-v3-beta11-history',JSON.stringify([{url:'/old.mp4',prompt:'PROMPT MUST NOT APPEAR',seed:2847193051}])));
    let ready=false,submitted;
    await page.route('**/api/kendo/status',route=>route.fulfill({json:{models_ready:ready,comfy_ready:true,progress:ready?100:42}}));
    await page.route('**/api/comfy/upload/image',route=>route.fulfill({json:{name:'reference.png',subfolder:''}}));
    await page.route('**/api/comfy/prompt',route=>{submitted=route.request().postDataJSON();route.fulfill({json:{prompt_id:'job'}})});
    await page.route('**/api/comfy/history/*',route=>route.fulfill({json:{}}));
    await page.goto('http://127.0.0.1:'+server.address().port);
    assert.equal(await page.locator('#video-enabled').isChecked(),false);
    assert.equal(await page.locator('#video-body').isHidden(),true);
    assert.equal(await page.locator('#seed-lock').isChecked(),false);
    assert.equal(await page.locator('#realism-enabled').isChecked(),true);
    assert.equal(await page.locator('#realism-weight').inputValue(),'0.75');
    assert.equal(await page.locator('#history').getByText('PROMPT MUST NOT APPEAR').count(),0);
    await page.locator('.history-actions button').click();
    assert.equal(await page.locator('#seed').inputValue(),'2847193051');
    const sample=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="640" height="640"><rect width="640" height="640" fill="#7d1730"/></svg>');
    await page.locator('#image-input').setInputFiles({name:'portrait.png',mimeType:'image/svg+xml',buffer:sample});
    assert.ok(await page.locator('#image-files img').evaluate(img=>img.getBoundingClientRect().width>=100));
    await page.locator('#prompt').fill('cinematic close-up');ready=true;
    await page.waitForFunction(()=>!document.querySelector('#generate').disabled);
    await page.locator('#generate').click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('ส่งเข้าคิวแล้ว'));
    assert.equal(submitted.prompt.realism.inputs.strength_model,0.75);
    assert.ok(!submitted.prompt.sage);
    assert.deepEqual(submitted.prompt.guider.inputs.model,['realism',0]);
    assert.deepEqual(submitted.prompt.schedule.inputs.model,['realism',0]);
    assert.match(submitted.prompt.reference.inputs.prompt,/^r34l1sm, /);
    assert.equal(submitted.prompt.noise.inputs.noise_seed,2847193051);
    assert.ok(!JSON.stringify(submitted).match(/SeedVR2|RTXVideo|FlashVSR|Upscale/));
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    assert.deepEqual(errors,[]);
    console.log('v3 beta.11 UI passed: v2 layout, default Realism 0.75, native attention, seed reuse and prompt-free history');
  }finally{if(browser)await browser.close();server.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
